language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any versions older than that should be considered deprecated.
# Don't bother testing with them. tip builds your code with the latest
# development version of Go. This can warn you that your code will break
# in the next version of Go. Don't worry! Later we declare that test runs
# are allowed to fail on Go tip.

# https://github.com/travis-ci/travis-ci/issues/9247
go:
  - "1.10"
  - master

# https://docs.travis-ci.com/user/languages/go/#Go-Import-Path
go_import_path: github.com/bbva/qed

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - go get -d ./...

script:
  # Skip tests dir: https://stackoverflow.com/questions/29064197/go-test-skip-directory
  - go test -v $(go list ./... | grep -v /tests)
