---
#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


- name: Download Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.8.0/prometheus-2.8.0.linux-amd64.tar.gz
    dest: /tmp
    keep_newer: true
    remote_src: true

- name: Install Prometheus binary
  copy:
    src: /tmp/prometheus-2.8.0.linux-amd64/prometheus
    dest: /usr/bin/prometheus
    remote_src: yes
    mode: preserve

- name: Create Prometheus system group
  group:
    name: prometheus
    system: yes
    gid: 210

- name: Create Prometheus system user
  user:
    name: prometheus
    system: yes
    uid: 210
    group: 210

- name: Create Prometheus work dir
  file:
    path: /var/lib/prometheus
    owner: prometheus
    group: prometheus
    mode: 0755
    state: directory

- name: Create Prometheus config dir
  file:
    path: /etc/prometheus
    state: directory

- name: Create Prometheus config
  template:
    dest: /etc/prometheus/prometheus.yml
    src: ../../templates/prometheus-config.yml.j2
    force: yes
  notify:
    - Restart Prometheus

- name: Install Prometheus systemd service unit file
  template:
    dest: /etc/systemd/system/{{ item }}
    src: ../../templates/{{ item }}.j2
  with_items:
    - prometheus.service
  notify:
    - Restart Prometheus

- name: Enable and run Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install Grafana
  yum:
      update_cache: yes
      name: https://dl.grafana.com/oss/release/grafana-6.0.1-1.x86_64.rpm

- name: Copy Grafana config and dashboards to remote
  copy:
      dest: /etc/grafana/provisioning/{{ item }}
      src: files/grafana/{{ item }}
      owner: root
      group: grafana
  with_items:
    - datasources/datasource.yml
    - dashboards/GoProcesses.json
    - dashboards/dashboard.yml
    - dashboards/Host.json
    - dashboards/QED.json
    - dashboards/RocksDB.json
    - dashboards/Cache.json
    - dashboards/RocksDBTables.json
    - dashboards/Workload.json
  register: grafana_config

- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: grafana_config.changed
