#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars.yml
  vars:
    # Set custom repo and branch for the docker build.
    # - qed_repo: 'https://github.com/suizman/qed.git'
    # - qed_repo_branch: 'cmd_workload'
  environment:
    - GOOS: linux
    - GOARCH: amd64
    - GO111MODULE: 'on'
    - CGO_LDFLAGS_ALLOW: '.*'
    - QED: 'go run ../../main.go'
  tasks:
    - include: tasks/common/build.yml
    - include: tasks/common/config.yml
  tags:
    - install
    - workload

- hosts: all
  remote_user: ec2-user
  gather_facts: false
  tasks:
    - set_fact:
        host_to_wait_for: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    - name: waiting for server to be alive
      wait_for:
        state: started
        port: 22
        host: "{{ host_to_wait_for }}"
        delay: 10
        timeout: 300
        connect_timeout: 300
        search_regex: OpenSSH
      delegate_to: localhost
      retries: 2
  tags:
    - install
    - workload

- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
    - name: Gather facts
      setup:
  tags:
    - install
    - prometheus
    - workload

- hosts: type_aws_instance
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/common/main.yml
  tags:
    - install

- hosts: all
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/qed/main.yml
  tags:
    - install

- hosts: workload
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/workload/main.yml
  tags:
    - install
    - workload

- hosts: inmemory-storage
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/inmemory_storage/main.yml
  tags:
    - install

- hosts: prometheus
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/prometheus/main.yml
  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        daemon_reload: yes
        state: restarted
  tags:
    - install
    - prometheus
